import Providers from "./Providers";
import Navbar from "./components/nav/Nav";
import Footer from "./components/footer/Footer";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <Navbar />
          <div className="container mx-auto">{children}</div>
          <Footer />
        </Providers>
      </body>
    </html>
  );
}