import Providers from "./Providers";
import Navbar from "./components/nav/Nav";
import Footer from "./components/footer/Footer";
import "./globals.css";
import { navBar } from "@/assets/texts";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {

  const navBarData = navBar[0]
  return (
    <html lang="en">
      <body>
        <Providers>
          <Navbar {...navBarData}/>
          <div>{children}</div>
          <Footer />
        </Providers>
      </body>
    </html>
  );
}